services:
  line_provider_app:
    build:
      context: .
      dockerfile: docker/LineProvider.dockerfile
    image: line_provider_app
    container_name: line_provider_app
    env_file: .env
    restart: always
    volumes:
      - ./line_provider:/app/src
    networks:
      - demo_network
    ports:
      - "8080:80"

  rabbitmq:
    user: 1000:1000
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    container_name: demo_rabbitmq
    networks:
      - demo_network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: rabbitmq:3-management-alpine
    ports:
      - "4672:5672"
      - "15672:15672"

networks:
  demo_network:
    external: false
    name: demo_network